### ISSUE TITLE
ES5 clients

### ISSUE THREAD

**Issue by elsassph** [web-infra-dev/rspack-dev-server#6]
`rspack-dev-server`'s `dist` code is transpiled to JS with modern features like spread, optional chaining... which fail on older devices (we support TV devices sporting Chrome 38+/Safari 6 equivalent browsers).

As the code is already transpiled, I couldn't find a way to use SWC in RSpack to convert those features to ES5, and have resorted to disable all hot features.

Ideally this library would emit maximally compatible code that will run on the oldest devices.

**Comment by LingyuCoder** [comment]
Seems to be a bug, the `dist/` code shoud run in Node, but the `ansiHTML.js` actually run on the client. It should be placed in the `client/`. I will try to fix it.
